Create `Continuous Deployment` pipeline

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -14,17 +14,18 @@ on:
       - 'settings.gradle'
 
 env:
-  USE_CACHE: 'true'
+  USE_DOCKER_CACHE: 'true'
   MAIN_IMAGE: 'ggbot'
   REGISTRY: 'ghcr.io'
   TMP_CACHE: 'cache-tmp'
 
   SET_VARIABLES: |
-    if [ 'true' = "$USE_CACHE" ]; then
-      build_image="${MAIN_IMAGE}-gradle-build"
+    if [ 'true' = "$USE_DOCKER_CACHE" ]; then
+      build_image_cache="${MAIN_IMAGE}-gradle-build-cache"
+      main_image_cache="${MAIN_IMAGE}-cache"
       echo "BUILD_IMAGE=${build_image}" >> $GITHUB_ENV
-      echo "BUILD_CONTAINER_CACHE=${REGISTRY}/${{ github.repository }}/${build_image}" >> $GITHUB_ENV
-      echo "MAIN_CONTAINER_CACHE=${REGISTRY}/${{ github.repository }}/${MAIN_IMAGE}" >> $GITHUB_ENV
+      echo "BUILD_IMAGE_CACHE=${REGISTRY}/${{ github.repository }}/${build_image_cache}" >> $GITHUB_ENV
+      echo "MAIN_IMAGE_CACHE=${REGISTRY}/${{ github.repository }}/${main_image_cache}" >> $GITHUB_ENV
     fi
 
 jobs:
@@ -62,15 +63,15 @@ jobs:
           password: ${{ secrets.CR_PAT }}
 
       - name: Pull cached images
-        if: ${{ 'true' == env.USE_CACHE }}
+        if: ${{ 'true' == env.USE_DOCKER_CACHE }}
         run: |
-          docker pull "$BUILD_CONTAINER_CACHE" || echo "::warning::Failed to pull ${BUILD_CONTAINER_CACHE}"
-          docker pull "$MAIN_CONTAINER_CACHE" || echo "::warning::Failed to pull ${MAIN_CONTAINER_CACHE}"
+          docker pull "$BUILD_IMAGE_CACHE" || echo "::warning::Failed to pull ${BUILD_IMAGE_CACHE}"
+          docker pull "$MAIN_IMAGE_CACHE" || echo "::warning::Failed to pull ${MAIN_IMAGE_CACHE}"
 
       - name: Build and run the container
         run: |
-          if [ 'true' = "$USE_CACHE" ]; then
-            cache_from="--cache-from ${BUILD_CONTAINER_CACHE} --cache-from ${MAIN_CONTAINER_CACHE}"
+          if [ 'true' = "$USE_DOCKER_CACHE" ]; then
+            cache_from="--cache-from ${BUILD_IMAGE_CACHE} --cache-from ${MAIN_IMAGE_CACHE}"
           fi
 
           # Set required envars
@@ -86,16 +87,16 @@ jobs:
           # shellcheck disable=SC2086
           ./bin/run.py --apply-migrations --detach $cache_from
 
-      - name: Tag and push the images
-        if: ${{ 'true' == env.USE_CACHE }}
+      - name: Tag and push the cache images
+        if: ${{ 'true' == env.USE_DOCKER_CACHE }}
         run: |
-          if docker tag "$BUILD_IMAGE" "$BUILD_CONTAINER_CACHE"; then
-            docker push "$BUILD_CONTAINER_CACHE" || echo "::warning::Failed to push ${BUILD_CONTAINER_CACHE}"
+          if docker tag "$BUILD_IMAGE" "$BUILD_IMAGE_CACHE"; then
+            docker push "$BUILD_IMAGE_CACHE" || echo "::warning::Failed to push ${BUILD_IMAGE_CACHE}"
           else
             echo "::warning::Failed to tag ${BUILD_IMAGE}"
           fi
-          if docker tag "$MAIN_IMAGE" "$MAIN_CONTAINER_CACHE"; then
-            docker push "$MAIN_CONTAINER_CACHE" || echo "::warning::Failed to push ${MAIN_CONTAINER_CACHE}"
+          if docker tag "$MAIN_IMAGE" "$MAIN_IMAGE_CACHE"; then
+            docker push "$MAIN_IMAGE_CACHE" || echo "::warning::Failed to push ${MAIN_IMAGE_CACHE}"
           else
             echo "::warning::Failed to tag ${MAIN_IMAGE}"
           fi
